[project]
name = "finance"
version = "1.0.0"
description = "Finance app to check portfolio."
dependencies = [
    "flask"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

